### PR TITLE
Fixes #186 Remove minify_exclude and load df.js on runtime

### LINKED ISSUE #186: hpp icon and editor wysiwyg doesn't work
Hello,

I am at version 2.1.1 Adyen module with the pull request https://github.com/Adyen/adyen-magento2/pull/181

Mode: Production
Bundling: Enabled
Merging: Disabled
Minifying: Enabled
Magento 2.1.5

Since I set up this pull request I don't see the payment hpp icons and I also noticed that the wysiwyg editor did not work too.

For wysiwyg editor : 
I have as error Refused to execute script from 'http://mysite.com/admin/admin/cms_page/edit/page_id/80/key/24c9a5d4193359efb292097503463c3cc970244ebf10f5a64ca0f17e7b40fea8//plugins/nonbreaking/editor_plugin.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled

For payment hpp icons : 
I have 404 not found for the icons.

When I'm in developer mode always work...

Have you an idea ?
Can you test if it works for you, please?

Did anyone else encounter this error?

Best regards

Philippe

### PR DESCRIPTION
**Pull request by lancergr**
**Description**
Remove minify_exclude and load df.js on runtime

**Tested scenarios**
checkout with Ratepay and Klarna in order to send the correct dfValue
tested minified and non-minified in wysiwyg

**Fixed issue**:  #186 #207

### CODE REVIEW

File: view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js [hunk 1]
```diff
@@ -91,28 +90,43 @@ define(
...
+
+                            // set device fingerprint value
+                            dfSet('dfValue', 0);
+                            // propagate this manually to knockoutjs otherwise it would not work
+                            dfValue($('#dfValue').val());
+                        }
+
                         adyenPaymentService.setPaymentMethods(response);
-                        if (JSON.stringify(response).indexOf("ratepay") > -1) {
+                        if(JSON.stringify(response).indexOf("ratepay") > -1) {
```
Comment (rikterbeek) [inline view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js]: Keep the space after the if statement

File: view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js [hunk 2]
```diff
@@ -91,28 +90,43 @@ define(
                     serviceUrl, JSON.stringify(payload)
                 ).done(
                     function (response) {
+                        function waitForDfSet() {
+                            // Wait for dfSet function to be loaded from df.js script
+                            if(typeof dfSet == "undefined") {
```
Comment (rikterbeek) [inline view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js]: space after if
