### PR TITLE
Release 6.1.0

### LINKED ISSUE #672: [PW-2384] Uncaught Error: Call to a member function getAdditionalInformation() on null in /vendor/adyen/module-payment/Model/AdyenThreeDS2Process.php:97
**Describe the bug**
I'm trying to follow these steps to integrate Adyen into our [Vue Storefront](https://github.com/DivanteLtd/vue-storefront) PWA and failing on step 4:
https://docs.adyen.com/plugins/magento-2/magento-pwa-storefront

Magento delivers the following error:
```
Fatal Error: 'Uncaught Error: Call to a member function getAdditionalInformation() on null in \/app\/web\/vendor\/adyen\/module-payment\/Model\/AdyenThreeDS2Process.php:97\nStack trace:\n#0 [internal function]: Adyen\\Payment\\Model\\AdyenThreeDS2Process->initiate(Array)\n#1 \/app\/web\/vendor\/magento\/module-webapi\/Controller\/Rest\/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)\n#2 \/app\/web\/vendor\/magento\/module-webapi\/Controller\/Rest.php(188): Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->process(Object(Magento\\Framework\\Webapi\\Rest\\Request\\Proxy))\n#3 \/app\/web\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#4 \/app\/web\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent('dispatch', Array)\n#5 \/app\/web\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}' in '\/app\/web\/vendor\/adyen\/module-payment\/Model\/AdyenThreeDS2Process.php' on line 97
```

This happens because I cannot get the `lastRealOrderId` [here](https://github.com/Adyen/adyen-magento2/blob/4a176d0457d3fc5d5aa42ccf992891eb8db1ed73/Model/AdyenThreeDS2Process.php#L170), since as I now, there is no `checkoutSession` ?! 
Is this really a bug or am I doing something wrong?

**To Reproduce**
1. Install Vue Storefront
2. Create Order
3. Post to `/V1/adyen/threeDS2Process`
4. See error in Magento `var/report/api/`

**Expected behavior**
It should return a correct response

### LINKED ISSUE #673: [PW-2230] Recurring payment run by cron expects browser info
**Describe the bug**
When cron makes a recurring payment, it is expected that HTTP_USER_AGENT has a value, and the payment is stopped.
We receive this:
ERROR: Notice: Undefined index: HTTP_USER_AGENT in /var/www/ordnad.se/vendor/adyen/module-payment/Helper/Requests.php on line 292

**To Reproduce**
The problem with reproducing this bug, is that subscription is not built into Magento 2. We are using the subscription module from Paradox Labs, but others have had the same problem (https://github.com/Adyen/adyen-magento2/issues/259), and so far, we have not seen that it has been fixed.

**Expected behavior**
The recurring order is placed without error.

**Additional context**
When asking Paradox Labs about this issue, I got this opinion/suggestion:
The proper fix in my opinion would be for them to move the 
<item name="browserinfo" xsi:type="string">Adyen\Payment\Gateway\Request\BrowserInfoDataBuilder</item>
parts in https://github.com/Adyen/adyen-magento2/blob/develop/etc/di.xml out of etc/di.xml and into etc/frontend/di.xml and etc/webapi_rest/di.xml.

### PR DESCRIPTION
**Pull request by cyattilakiss**
**Description**
#679 [PW-2174] Removing sync order cancellation for 3DS1 failure response 
#682 [PW-2257] Check availability of userAgent and acceptHeader before assigning 
#688 [PW-2275] added visadankort.png logo 
#691 [PW-2229] PWA using session for AdyenThreeDS2Process 
#692 [PW-2199] Add configuration to toggle order cancellation on notification processing 
#685 Add extra check to submit button 
#704 [PW-2360] Removing decode of paywithgoogle.token, expected format is JSON string 
#706 [PW-2382] Checking if the _order object is set before attempting to add comment 
#707 [PW-2379]: Declaring configuration values as sensitive or system-specific 

**Fixed issue**:  
#488 Order status pending when payment cancelled and later authorized
Closes #673 Recurring payment run by cron expects browser info
Closes #672 Uncaught Error: Call to a member function getAdditionalInformation() on null in /vendor/adyen/module-payment/Model/AdyenThreeDS2Process.php:97
#662 Alternative payment methods allow user to bypass required payment address

### CODE REVIEW

File: Model/Cron.php [hunk 1]
```diff
@@ -829,6 +838,11 @@ protected function _retrieveLast4DigitsFromReason($reason)
      */
     protected function _holdCancelOrder($ignoreHasInvoice)
     {
+        if (!$this->configHelper->getNotificationsCanCancel($this->_order->getStoreId())) {
+            $this->_adyenLogger->addAdyenNotificationCronjob('Order can not be canceled based on the plugin configuration');
```
Comment (acampos1916) [inline Model/Cron.php:842]:
```suggestion
            $this->_adyenLogger->addAdyenNotificationCronjob('Order cannot be canceled based on the plugin configuration');
```

**Comment by cyattilakiss** [comment]
Found a breaking change for PWA users removing the support to retrieve the order from the session here: https://github.com/Adyen/adyen-magento2/pull/691/files#diff-f74341f02dc1e1a11c330cdc50f98f13L161-L174
I will fix in the next couple of hours.
