### PR TITLE
[ECP-8799] [V9] Fix refund openinvoice after cart expired

### LINKED ISSUE #2367: ECP-8799 [V9] Cannot refund (via Magento) with Alternative methods
**Describe the bug**

We cannot refund online via creditmemo creation page (only button `Refund offline` is present) for alternative payments (tested on alma and google pay.).

It works fine for adyen_cc.

**To Reproduce**
1. Try to refund an order paid with googlepay

**Expected behavior**

`Refund online` button is there.

**Magento version**
2.4.6-p3

**Plugin version**
9.0.2

### PR DESCRIPTION
**Pull request by hossam-adyen**
**Description**
Fix refund & capture an openInvoice order when the quote expired

**Tested scenarios**
Place openInvoice order and refund it successfully when the related quote expired

Fixes  #2367

### CODE REVIEW

File: Gateway/Request/RefundDataBuilder.php [hunk 1]
```diff
@@ -168,7 +168,7 @@ public function build(array $buildSubject): array
             );
 
             if ($this->adyenHelper->isPaymentMethodOpenInvoiceMethod($brandCode)) {
-                $openInvoiceFieldsCreditMemo = $this->openInvoiceHelper->getOpenInvoiceData($creditMemo->getOrder());
+                $openInvoiceFieldsCreditMemo = $this->openInvoiceHelper->getOpenInvoiceDataFromPayment($payment);
```
Comment (candemiralp) [inline Gateway/Request/RefundDataBuilder.php:171]: What would you think about using `getCreditmemosCollection()` for refunds? That allows us to get correct items. Last refunded items might be different than last invoiced items.

Comment (hossam-adyen) [reply Gateway/Request/RefundDataBuilder.php]: I've inject the credit memo invoice, to be use instead of the last invoice

```
$openInvoiceFieldsCreditMemo = $this->openInvoiceHelper->getOpenInvoiceDataFromPayment($payment, $creditMemo->getInvoice());
```

**Review by RokPopov — APPROVED** [review]

**Review by candemiralp — DISMISSED** [review]

**Review by candemiralp — APPROVED** [review]

**Review by khushboo-singhvi — APPROVED** [review]
