### PR TITLE
[PW-5682] Added refund adjustment functionality for openinvoice data

### LINKED ISSUE #982: "Invalid amount specified" causes "Undefined index: pspReference"
**Describe the bug**
Creating an invoice with zero grand total results in `Undefined index: pspReference` error

**To Reproduce**
* Create an invoice using  `\Magento\Sales\Model\InvoiceOrder::execute` (`capture := true`) for an order paid with this module, so that grand total is zero (e.g. invoice less than ordered, where original order grand total is partially paid via customerbalance)
* The gateway responds with `https://docs.adyen.com/development-resources/error-codes#137-invalid-amount-specified` (as expected, I would assume)

**Expected behavior**
I would expect error 137 to be detected and rendered to a readable exception

**Actual behavior**
The error is silenced and I get the nasty "Undefined index" notice-turned-to-exception below:

```
[2021-03-10 09:46:04] report.CRITICAL: Notice: Undefined index: pspReference in /srv/vendor/adyen/module-payment/Gateway/Response/PaymentCaptureDetailsHandler.php on line 42 
```

**Magento version**
2.4.1

**Plugin version**
6.6.9

---
But looking at the code within https://github.com/Adyen/adyen-magento2/blob/develop/Gateway/Validator/CaptureResponseValidator.php I see that `$isValid` is set to `true` no matter what, in fact the resulting `\Magento\Payment\Gateway\Validator\ResultInterface` will contain the non-empty error array _and_ isValid == true... is that deliberate? Because I see a similar patter in all the sibling Validators within `\Magento\Payment\Gateway\Validator`

### LINKED ISSUE #1123: [PW-5682] Adjustment refund is not working for orders paid with Klarna
**Describe the bug**

**To Reproduce**
1. Place an order with Klarna (klarna_account) and wait for it to be captured
2. Go to invoice and click on Credit Memo action button
3. Scroll down to Adjustment Refund, set a value and do not refund any items.
4. Click on "Refund Online" button
5. You will have the following error:

`Notice: Undefined index: pspReference in /var/www/html/vendor/adyen/module-payment/Gateway/Response/PaymentRefundDetailsHandler.php on line 43`

**Expected behavior**
Adjustment refund should work properly with Klarna too.

**Magento version**
2.3.7

**Plugin version**
7.0.1

**Screenshots**

Screenshot 2021-08-03 at 18 01 31

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 91.0.4472.114

### PR DESCRIPTION
**Pull request by tnaber**
**Description**
An ```Undefined index: pspReference``` error is thrown when setting a refund adjustment or fee when using a payment method that uses the openinvoice dataflow. This is due to 2 problems. Firstly, as defined by #982, the error is not correctly handled. Magento continues until it tries to fetch the pspReference, which is not there as an error is returned. To fix this a correct error handler is introduced. Secondly, as defined in #1123, no lines are added to the openinvoice data for refund adjustments, resulting in: ```"additionalData":{"openinvoicedata.numberOfLines":0,"acquirerReference":null}```, which triggers an error (again showing the Underfined index error). This has been fixed by adding a method which constructs the correct lines for the openinvoice data for both a negative and positive adjustment.

A consideration: right now 'Field 'amount' is not valid.' is thrown when the value send to the server was invalid. As no error code or other data is returned this is the only info that can be displayed. Is this up to standards?

**Tested scenarios**
- Normal refund
- Refund with 0 grand total
- Refund with positive adjustment
- Refund with negative adjustment
- Refund with both positive and negative adjustment (when resulting in negative or positive grandtotal)

**Fixed issue**:
Closes #1123
Closes #982

### CODE REVIEW

**Review by manuel-EGO — DISMISSED** [review]
Have reviewed and tested the changes, managed to successfully do partial refunds on Adyen HPP methods

**Review by peterojo — DISMISSED** [review]

File: Gateway/Request/RefundDataBuilder.php [hunk 1]
```diff
@@ -241,6 +241,28 @@ protected function getOpenInvoiceData($payment)
...
+        // Adjustment positive
+        if ($creditMemo->getAdjustment() != 0) {
+            $description = "Adjustment";
+            if ($creditMemo->getAdjustmentPositive() > 0 && $creditMemo->getAdjustmentNegative() > 0) {
+                $description .= " - Positive | Negative";
+            } elseif ($creditMemo->getAdjustmentPositive() > 0) {
+                $description .= " - Positve";
+            } elseif ($creditMemo->getAdjustmentNegative() > 0) {
+                $description .=  " - Negative";
+            }
```
Comment (acampos1916) [inline Gateway/Request/RefundDataBuilder.php:253]: Maybe this is cleaner and still works the same way
```suggestion
        if ($creditMemo->getAdjustment() != 0) {
            $positive = $creditMemo->getAdjustmentPositive() > 0 ? 'Positive' : '';
            $negative = $creditMemo->getAdjustmentNegative() > 0 ? 'Negative' : '';
            $description = "Adjustment - " . implode(' | ', array_filter([$positive, $negative]));
```

File: Gateway/Request/RefundDataBuilder.php [hunk 2]
```diff
@@ -241,6 +241,28 @@ protected function getOpenInvoiceData($payment)
...
+
+            ++$count;
+            $formFields = $this->adyenHelper->createOpenInvoiceLineAdjustment(
+                $formFields,
+                $count,
+                $description,
+                $creditMemo->getAdjustment(),
```
Comment (acampos1916) [inline Gateway/Request/RefundDataBuilder.php:260]: Will this amount take the Charged Currency config in consideration?

File: Gateway/Response/PaymentRefundDetailsHandler.php [hunk 3]
```diff
@@ -39,6 +39,10 @@ public function handle(array $handlingSubject, array $response)
         $payment = $payment->getPayment();
 
         foreach ($response as $singleResponse) {
+            if (isset($singleResponse['error'])) {
+                throw new \Magento\Framework\Exception\LocalizedException(__($singleResponse['error']));
```
Comment (acampos1916) [inline Gateway/Response/PaymentRefundDetailsHandler.php:43]: If you can confirm that this error is already logged in a file I think it is better to show a generic error message `The refund failed, check the logs for details.`, that way your concern about the 'Field amount' error is also solved.

**Review by acampos1916 — COMMENTED** [review]
Left a few comments.

File: Gateway/Request/RefundDataBuilder.php (hunk 2 above)
Comment (tnaber) [reply Gateway/Request/RefundDataBuilder.php:255]: Same problem as #1138 (#1197) for all refund based actions

File: Gateway/Response/PaymentRefundDetailsHandler.php (hunk 3 above)
Comment (tnaber) [reply Gateway/Response/PaymentRefundDetailsHandler.php]: Updated this

**Comment by tnaber** [comment]
@peterojo and @acampos1916, this PR has now been updated to use the correct currency when a different display currency is set. Tests are included.

File: Gateway/Request/RefundDataBuilder.php [hunk 4]
```diff
@@ -110,7 +114,7 @@ public function build(array $buildSubject)
                 $orderPaymentCollection->addPaymentFilterDescending($payment->getId());
             } elseif ($refundStrategy == "3") {
                 // refund based on ratio
-                $ratio = $buildSubjectAmount / $orderAmountCurrency->getAmount();
+                $ratio = $buildSubjectAmount / $amount->getAmount();
```
Comment (peterojo) [inline Gateway/Request/RefundDataBuilder.php:117]: Since `$amount` is already a float, this might break. :)

File: Gateway/Request/RefundDataBuilder.php [hunk 5]
```diff
@@ -228,15 +230,34 @@ protected function getOpenInvoiceData($payment)
...
+                $shippingAmountCurrency->getCurrencyCode(),
+                $payment
+            );
+        }
+
+        // Adjustment
+        $adjustmentAmountCurrency = $this->chargedCurrency->getCreditMemoAdjustmentAmountCurrency($creditMemo);
+        if ($adjustmentAmountCurrency->getAmount() != 0) {
+            $positive = $adjustmentAmountCurrency->getAmount() > 0 ? 'Positive' : '';
+            $negative = $adjustmentAmountCurrency->getAmount() > 0 ? 'Negative' : '';
```
Comment (peterojo) [inline Gateway/Request/RefundDataBuilder.php:251]:
```suggestion
            $negative = $adjustmentAmountCurrency->getAmount() < 0 ? 'Negative' : '';
```

File: Helper/ChargedCurrency.php [hunk 6]
```diff
@@ -141,29 +142,100 @@ public function getInvoiceItemAmountCurrency(Invoice\Item $item)
...
+     */
+    public function getCreditMemoAdjustmentAmountCurrency(CreditmemoInterface $creditMemo)
+    {
+        $chargedCurrency = $creditMemo->getOrder()->getAdyenChargedCurrency();
+        if ($chargedCurrency == self::BASE) {
+            return new AdyenAmountCurrency(
+                $creditMemo->getBaseAdjustment(),
+                $creditMemo->getBaseCurrencyCode(),
+                null,
+                0
```
Comment (peterojo) [inline Helper/ChargedCurrency.php:181]: I think you can remove the last 2 arguments since they default to 0

File: Helper/ChargedCurrency.php [hunk 7]
```diff
@@ -141,29 +142,100 @@ public function getInvoiceItemAmountCurrency(Invoice\Item $item)
...
+            );
+        }
+        return new AdyenAmountCurrency(
+            $creditMemo->getAdjustment(),
+            $creditMemo->getOrderCurrencyCode(),
+            null,
+            0
```
Comment (peterojo) [inline Helper/ChargedCurrency.php:188]: same thing here https://github.com/Adyen/adyen-magento2/pull/1213/files#r744728909

File: Helper/Data.php [hunk 8]
```diff
@@ -1285,6 +1285,43 @@ public function createOpenInvoiceLineShipping(
         );
     }
 
+    /**
+     * @param $formFields
+     * @param $count
+     * @param $order
```
Comment (peterojo) [inline Helper/Data.php:1291]:
```suggestion
     
```

File: Helper/Data.php [hunk 9]
```diff
@@ -1285,6 +1285,43 @@ public function createOpenInvoiceLineShipping(
         );
     }
 
+    /**
```
Comment (peterojo) [inline Helper/Data.php:1288]: Could you please add a line to describe what this function does here?

File: Test/Unit/Helper/ChargedCurrencyTest.php [hunk 10]
```diff
@@ -257,32 +263,61 @@ protected function setUp(): void
...
             ->setMethods([
                 'getBasePrice',
                 'getPrice',
-                'getInvoice',
                 'getCreditMemo',
+                'getOrder',
                 'getBaseTaxAmount',
                 'getTaxAmount',
-                'getQty'
+                'getQty',
```
Comment (peterojo) [inline Test/Unit/Helper/ChargedCurrencyTest.php:313]: let's leave out the trailing commas
```suggestion
                'getQty'
```

**Review by peterojo — APPROVED** [review]

**Review by acampos1916 — APPROVED** [review]
