### PR TITLE
[ECP-8453] Null merchant reference causes failure on the webhook processing

### LINKED ISSUE #2066: [PW-8453] Argument 1 passed to Adyen\\Payment\\Helper\\Order::getOrderByIncrementId() must be of the type string, null given
**Describe the bug**
In some cases, a notification does not have a merchant reference, and this causes an error in the process of executing the notification.

Example: 
```bash
[2023-05-23 15:07:04] AdyenLoggerTest.ADYEN_NOTIFICATION: Processing REPORT_AVAILABLE notification 6553468 {"merchantReference":null,"pspReference":"settlement_detail_report_batch_1413_20230523.csv"} {"uid":"d3f7dfa"}

[2023-05-23 15:07:04] report.CRITICAL: Error when running a cron job {"exception":"[object] (RuntimeException(code: 0): Error when running a cron job at /app/kny322hrt24u6/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:367, TypeError(code: 0): Argument 1 passed to Adyen\\Payment\\Helper\\Order::getOrderByIncrementId() must be of the type string, null given, called in /app/kny322hrt24u6/vendor/adyen/module-payment/Helper/Webhook.php on line 134 at /app/kny322hrt24u6/vendor/adyen/module-payment/Helper/Order.php:613)"} []
```
This behavior causes row in table "adyen_notification" to get stuck with "processing" = 1 forever. 

**To Reproduce**
1. Use an order with "merchant_reference = null".
2. Run cron responsible for processing adyen_notification.

**Expected behavior**
It is expected that the notification will be completed or that some action will be taken, preventing the notification from being stuck in processing forever.

**Magento version**
2.4.2

**Plugin version**
8.9.0

**Screenshots**
Captura de tela de 2023-05-23 15-55-09

image

bb54be3c-be28-4725-bb07-fd452d9c26c0

**Additional context**
As i show in the screenshots, the code:

```php
$order = $this->orderHelper->getOrderByIncrementId($notification->getMerchantReference());
```

should be inside the try catch block.

### PR DESCRIPTION
**Pull request by RokPopov**
**Description**
Currently, [webhook](https://github.com/Adyen/adyen-magento2/blob/efe1f69b24d056ec370cea225970f44083dd036a/Helper/Webhook.php) helper throws an exception if the merchant reference is empty in the notification body and causes notification stays on Processing forever.

With this PR we are checking whether the merchant reference is set before executing the processing webhook logic.

**Tested scenarios**
- process the notification with the merchant reference
- process the notification without the merchant reference

Fixes  #2066

### CODE REVIEW

**Review by candemiralp — APPROVED** [review]

**Review by khushboo-singhvi — APPROVED** [review]

File: Helper/Webhook.php [hunk 1]
```diff
@@ -109,20 +109,7 @@ public function __construct(
...
-                    $notification->getEntityId(),
-                ), [
-                    'merchantReference' => $notification->getMerchantReference(),
-                    'pspReference' => $notification->getPspreference()
-                ],
-            );
-
+        // check if merchant reference is set
         if (is_null($notification->getMerchantReference())) {
             $errorMessage = sprintf(
```
Comment (hossam-adyen) [inline Helper/Webhook.php:114]: I don't think this case should be marked as error, as we will just skip this notification from processing and log it

```suggestion
            $warningMessage = sprintf(
```

**Review by hossam-adyen — APPROVED** [review]
