### PR TITLE
[PW-6239] - Set the Adyen configured order status on: Order Creation & Fix Invoice Observer

### LINKED ISSUE #1593: InvoiceObserver not working with pending banktransfer payments
Adyen 8.3.0
Magento 2.4.3-p1

We still face the problem that non-Adyen payment methods will change order status as is was an Adyen payment.
We see this problem in the native "banktransfer" method.
When we create an order with banktransfer the order status will be set as the Adyen configuration and not what we expected it should be (pending payment)
One think to keep in mind. We made 1 change in the banktransfer.php model. We added protected $_canCapture = true; so we can keep invoices as pending unit the customer pays the payment by manual bank transfer.
So when we create the banktranfer invoice we do not capture the payment so the invoices will keep pending state and it is in this scenario that the order status will kep the Adyen configuration "approved". It shoud be "pending payment". When we "capture" then banktransfer the status will correctly be "processing".

Skærmbillede 2022-07-04 kl  10 06 05
Skærmbillede 2022-07-04 kl  10 04 30
Skærmbillede 2022-07-04 kl  10 04 25
Skærmbillede 2022-07-04 kl  10 02 18

### LINKED ISSUE #1595: Capture webhook not working in 8.3.0
In the latest version 8.3.0 we do not get the capture webhook.
We get this error when we try in magneto 2 to reprocess the webhook for capture.

Error: Call to a member function pay() on null in /var/www/droner.dk/public_html/vendor/magento/module-sales/Model/Order/Invoice.php:368
Stack trace:
#0 /var/www/droner.dk/public_html/generated/code/Magento/Sales/Model/Order/Invoice/Interceptor.php(149): Magento\Sales\Model\Order\Invoice->pay()
#1 /var/www/droner.dk/public_html/vendor/adyen/module-payment/Helper/Invoice.php(196): Magento\Sales\Model\Order\Invoice\Interceptor->pay()
#2 /var/www/droner.dk/public_html/vendor/adyen/module-payment/Helper/Webhook.php(1821): Adyen\Payment\Helper\Invoice->handleCaptureWebhook()
#3 /var/www/droner.dk/public_html/vendor/adyen/module-payment/Helper/Webhook.php(420): Adyen\Payment\Helper\Webhook->handleManualCapture()
#4 /var/www/droner.dk/public_html/vendor/adyen/module-payment/Helper/Webhook.php(344): Adyen\Payment\Helper\Webhook->handleOrderTransition()
#5 /var/www/droner.dk/public_html/vendor/adyen/module-payment/Controller/Adminhtml/Notifications/WebhookReprocess.php(71): Adyen\Payment\Helper\Webhook->processNotification()
#6 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess->execute()
#7 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->___callParent()
#8 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->Magento\Framework\Interception\{closure}()
#9 /var/www/droner.dk/public_html/generated/code/Adyen/Payment/Controller/Adminhtml/Notifications/WebhookReprocess/Interceptor.php(23): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->___callPlugins()
#10 /var/www/droner.dk/public_html/vendor/magento/framework/App/Action/Action.php(111): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->execute()
#11 /var/www/droner.dk/public_html/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#12 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#13 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->___callParent()
#14 /var/www/droner.dk/public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->Magento\Framework\Interception\{closure}()
#15 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#16 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->Magento\Framework\Interception\{closure}()
#17 /var/www/droner.dk/public_html/generated/code/Adyen/Payment/Controller/Adminhtml/Notifications/WebhookReprocess/Interceptor.php(32): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->___callPlugins()
#18 /var/www/droner.dk/public_html/vendor/magento/framework/App/FrontController.php(245): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->dispatch()
#19 /var/www/droner.dk/public_html/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#20 /var/www/droner.dk/public_html/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#21 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#22 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#23 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#24 /var/www/droner.dk/public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#25 /var/www/droner.dk/public_html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#26 /var/www/droner.dk/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#27 /var/www/droner.dk/public_html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#28 /var/www/droner.dk/public_html/pub/index.php(29): Magento\Framework\App\Bootstrap->run()
#29 {main}

### PR DESCRIPTION
**Pull request by candemiralp**
**Description**

`order_status` parameter in Adyen configuration wasn't effective for the new orders. Magento expects correct configuration path for all payment methods. In example, `payment/adyen_cc/order_status`. However, configuration was only updating `payment/adyen_abstract/order_status`, which wasn't taken into consideration. 

New observer is responsible for updating related `order_status` path for all payment methods.

`InvoiceObserver` is not triggered for Adyen payments but triggered for non-Adyen payments, which blocks the manual capture and invoice creation process.

Change the return values of the related method.

**Fixed issue**:
Closes #1593 
Closes #1595

### CODE REVIEW

File: Helper/PaymentMethods.php [hunk 1]
```diff
@@ -155,27 +165,39 @@ public function getPaymentMethods($quoteId, $country = null)
...
+     * @return string[]
+     */
+    public function getAdyenPaymentMethods() : array
+    {
+        $paymentMethods = $this->dataHelper->getPaymentMethodList();
+
+        $filtered = array_filter(
+            $paymentMethods,
+            function ($key) {
+                return str_starts_with($key, self::ADYEN_PREFIX);
```
Comment (michaelpaul) [inline Helper/PaymentMethods.php:193]: The `str_starts_with` function is from PHP 8. Since we support Magento 2.3 and PHP 7, this might need some tweaks.

File: Helper/PaymentMethods.php [hunk 2]
```diff
@@ -155,27 +161,39 @@ public function getPaymentMethods($quoteId, $country = null)
...
-    }
-
     /**
      * @param string $methodCode
      * @return bool
      */
     public function isAdyenPayment(string $methodCode): bool
     {
-        if(in_array($methodCode, $this->getAdyenPaymentCodes())) {
+        if(in_array($methodCode, $this->getAdyenPaymentMethods())) {
```
[the remark this answers is not in the document]
Comment (candemiralp) [reply Helper/PaymentMethods.php:174]: This will be solved in PW-6890.

File: Helper/PaymentMethods.php (hunk 1 above)
Comment (candemiralp) [reply Helper/PaymentMethods.php:193]: Thanks for the comment @michaelpaul. I will use `strpos()` for this one.

**Review by peterojo — DISMISSED** [review]

**Review by peterojo — DISMISSED** [review]

**Review by acampos1916 — APPROVED** [review]
