### PR TITLE
[ECP-9491] Refactor instantiating AdyenCheckout library and components

### LINKED ISSUE #2581: [ECP-9154][ECP-9491] Excessive network usage while making a virtual purchase
**Describe the bug**
When placing an order for a virtual product adyen.js makes ~100 calls to each of dfp.1.0.0.html, fingerprintjs2.js, and risk.1.0.0.js.  This transfers 2.8MB over the network.  Purchasing a physical product makes ~6 calls on the same environment.

**To Reproduce**
Assuming a clean Magento 2 installation with only the Adyen plugin installed and a sample virtual product.
1. Add virtual product to cart
2. Go to checkout
3. Observe network tab

**Expected behavior**
I would expect that 1 call would be sufficient for these.

**Magento version**
2.4.6-p4

**Plugin version**
9.3.0

**Screenshots**
Sorry for the resolution - Github limits to 10MB.
https://github.com/Adyen/adyen-magento2/assets/1679978/0a04b624-5149-45c8-90c6-7adaadbc84a7

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.1.1 (23B81)
 - Browser: Chrome
 - Version: 123.0.6312.107

### LINKED ISSUE #2766: Excessive calls (100+ per asset) to checkoutShopper assets
**Describe the bug**
The checkout is making an excessive amount of network requests to the `https://checkoutshopper-test.adyen.com/checkoutshopper/assets/...` domain. We are seeing over 100 requests each to `dfp.1.0.0.html` `fingerprintjs2.js` `risk.1.0.1.js`. See attached Google Drive link for example

On Safari this is causing a long running loader and a flood of console errors from `fingerprintjs2.js` `There are too many active WebGL contexts on this page, the oldest context will be lost.`
And on Chrome similar network activity without the console spam / long running loader. 

**To Reproduce**
1. Navigate to checkout
2. Wait for payment methods to load
3. View Network tab and filter for checkoutShopper

**Expected behavior**
A single request for each checkoutShopper asset. 

**Magento version**
2.4.6-p8

**Plugin version**
9.9.1

**Screenshots**
https://drive.google.com/file/d/1SMHvnWSeVb1_uUu2kl2iAn0mXvQVNXuF/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: MacOS 15.0
 - Browser Chromium: 129.0.6668.89 + Safari 18.0

**Additional context**
From an initial quick look, it appears we are accidentally building the checkout component for every payment method instead of just once.

Placing a breakpoint on the subscribe method shows a subscription being bound for every payment method (101 times), even if they are not used on the merchants account. 

If you place a breakpoint on the `createCheckoutComponent` method, you can step through and switch to the network tab and see another set of the js files being loaded.

https://github.com/Adyen/adyen-magento2/blob/main/view/frontend/web/js/view/payment/method-renderer/adyen-pm-method.js#L71

https://github.com/Adyen/adyen-magento2/blob/main/view/frontend/web/js/view/payment/method-renderer/adyen-pm-method.js#L86

https://github.com/Adyen/adyen-magento2/blob/main/view/frontend/web/js/view/payment/method-renderer/adyen-pm-method.js#L86

### PR DESCRIPTION
**Pull request by candemiralp**
**Description**

The plugin currently builds `AdyenCheckout` library object as much as the number of the payment methods enabled on the checkout and mounts all of the payment components at the same time after rendering the checkout. 

This results in delays on the checkout since `AdyenCheckout` library makes multiple calls to `checkoutshopper` endpoints after instantiation for collecting data for risk calculation. This causes a drastic performance degradation on the checkout page.

Ideally, `AdyenCheckout` library object should be instantiated after a shopper selects an Adyen payment method. This PR introduces a refactoring which changes the logic of instantiating the `AdyenCheckout` library and mount payment method components.

**Tested scenarios**

- Rendering checkout and selecting a payment method triggers single call to `checkoutshopper`
- Pre-selected payment method triggers single call to `checkoutshopper`
- `checkoutshopper` endpoint is not called if no Adyen payment method is selected

Fixes #2766 
Fixes #2581

### CODE REVIEW

**Review by khushboo-singhvi — DISMISSED** [review]

**Review by peterojo — DISMISSED** [review]

File: view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js [hunk 1]
```diff
@@ -132,19 +166,31 @@ define(
...
+
+                if (!this.getClientKey) {
                     return false;
                 }
 
-                self.installments(0);
-
-                // installments
-                let allInstallments = self.getAllInstallments();
+                this.installments(0);
```
Comment (Januszpl) [inline view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js:188]: @candemiralp I'm getting error from template `cc-form.html` template related to undefined variable, if installments aren't set to 0 in `defaults`

```
            defaults: {
                template: 'Adyen_Payment/payment/cc-form',
                installment: '', // keep it until the component implements installments
                installments: 0,
                orderId: 0, // TODO is this the best place to store it?
                storeCc: false,
                modalLabel: 'cc_actionModal'
            },
```

Comment (candemiralp) [reply view/frontend/web/js/view/payment/method-renderer/adyen-cc-method.js:188]: Hello @Januszpl,

I will get back to you after checking this point.

Best Regards,
Can

**Review by peterojo — DISMISSED** [review]

**Review by peterojo — APPROVED** [review]

**Review by khushboo-singhvi — APPROVED** [review]
