### PR TITLE
[ECP-8788] Use default value for recurringProcessingModel if no value set on token details

### LINKED ISSUE #2362: [ECP-8788] Required field 'recurringProcessingModel' is not provided during using saved cc payment
**Describe the bug**
When attempting to make a recurring payment on Magento Adyen, an error occurs. After selecting a stored credit card from the dropdown and clicking "Place order," the message "Error with payment method, please select a different payment method" is displayed. 
Adyen info log:
AdyenLoggerTest.INFO: Request to Adyen API /payments {"apiVersion":"v70","livePrefix":"***","body":{"shopperReference":"***","reference":"***"}} {"uid":"9957baf"}

Magento logs:
[2023-11-22T07:28:07.465879+00:00] AdyenLoggerTest.ERROR: Required field 'recurringProcessingModel' is not provided. [] {"uid":"9957baf"}

**To Reproduce**
Customer has a saved cc
Customer select the saved cc
Customer click on "Place order"
The order is not placed and the message "Error with payment method, please select a different payment method" appeared

**Expected behavior**
Customer should be able to create  an order using save cc

**Magento version**
Magento 2.4.6-p3

**Plugin version**
8.22.4

**Desktop (please complete the following information):**
 - Windows 11
 - Chrome
 - 119.0.6045.160 (Latest stable)

**Additional context**
Card Tokenization is ON/OFF, doesn't affect the result

### PR DESCRIPTION
**Pull request by candemiralp**
**Description**

After migrating from earlier version of the plugin (ex: 8.3.5), missing `recurringProcessingModel` exception has been seen. This has been caused by missing information on token details, since earlier versions of the plugin didn't used to add `recurringProcessingModel` key to token details.

This PR introduces default value to `recurringProcessingModel` field if there is no information on token details.

**Tested scenarios**

- Tokenised payments

Fixes #2362

### CODE REVIEW

File: Gateway/Request/RecurringVaultDataBuilder.php [hunk 1]
```diff
@@ -26,18 +29,26 @@ class RecurringVaultDataBuilder implements BuilderInterface
...
     }
 
     /**
      * @param array $buildSubject
      * @return array
+     * @throws LocalizedException
      */
     public function build(array $buildSubject)
     {
-        $requestBody = [];
```
Comment (hossam-adyen) [inline Gateway/Request/RecurringVaultDataBuilder.php:40]: why ?

**Review by hossam-adyen — APPROVED** [review]

**Review by RokPopov — APPROVED** [review]
